# Generated by Django 4.1.1 on 2022-10-10 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
